#!/usr/bin/env bash
# Move the Docker image to a newer Arch Linux Archive snapshot and re-pin the
# Python packages to match.
#
#   scripts/update_docker_pins.sh [YYYY/MM/DD]
#
# The date selects the snapshot at https://archive.archlinux.org/repos/ and
# defaults to yesterday (UTC), since today's snapshot may not exist yet.
#
# Steps:
#   1. set ARG ARCH_SNAPSHOT in the Dockerfile
#   2. build the image with the direct dependencies from requirements.in unpinned
#   3. write `pip freeze --local` of that image to requirements.txt
#   4. rebuild with the pinned file (cached up to the pip layer) and run the tests
#   5. print the resolved system versions for the changelog
#
# Dockerfile and requirements.txt are restored if any step fails. The base
# image digest is left alone: the snapshot date decides every package version,
# the digest only has to keep resolving.
set -euo pipefail

cd "$(dirname "$0")/.."

snapshot="${1:-$(date -u -d yesterday +%Y/%m/%d)}"
if [[ ! "$snapshot" =~ ^[0-9]{4}/[0-9]{2}/[0-9]{2}$ ]]; then
    echo "usage: $0 [YYYY/MM/DD]" >&2
    exit 1
fi
image="dqi-kit:pin-update"

cp Dockerfile Dockerfile.pin-backup
cp requirements.txt requirements.txt.pin-backup
restore() {
    echo "update failed, restoring Dockerfile and requirements.txt" >&2
    mv Dockerfile.pin-backup Dockerfile
    mv requirements.txt.pin-backup requirements.txt
}
trap restore ERR

echo "==> 1/5 pinning the Arch snapshot to ${snapshot}"
sed -i -E "s#^ARG ARCH_SNAPSHOT=.*#ARG ARCH_SNAPSHOT=${snapshot}#" Dockerfile
grep -q "^ARG ARCH_SNAPSHOT=${snapshot}\$" Dockerfile

echo "==> 2/5 building with unpinned direct dependencies (this pulls SageMath; ~10 min)"
cp requirements.in requirements.txt
docker build -t "$image" .

echo "==> 3/5 freezing the resolved Python packages into requirements.txt"
{
    echo "# Python packages installed into the image's venv on top of the Arch packages"
    echo "# (numpy, scipy and networkx come with the sagemath package and are pinned by"
    echo "# the Arch Linux Archive snapshot date in the Dockerfile). Generated by"
    echo "# scripts/update_docker_pins.sh from requirements.in for snapshot ${snapshot}."
    docker run --rm "$image" pip freeze --local | LC_ALL=C sort
} > requirements.txt

echo "==> 4/5 rebuilding with the pinned file and running the tests"
docker build -t "$image" .
docker run --rm "$image" python -m pytest tests -q -p no:cacheprovider

echo "==> 5/5 resolved versions (for the changelog)"
docker run --rm "$image" pacman -Q sagemath gap python python-numpy python-scipy python-networkx
grep -E '^(ldpc|ortools|simanneal|pytest)==' requirements.txt

trap - ERR
rm -f Dockerfile.pin-backup requirements.txt.pin-backup
echo
echo "done; review the changes and update CHANGELOG.md:"
git --no-pager diff --stat -- Dockerfile requirements.txt
